#include<stdio.h>
main()
{
    int i,j,k,count=0;
    for(i=1;i<5;i++)
    {
        for(j=1;j<5;j++)
        {
            if(i!=j)
            for(k=1;k<5;k++)
            {
                if(i!=k&&j!=k)
                {
                    count++;
                    printf("%d%d%d\n",i,j,k);
                }
            }
        }
    }
    printf("%d",count);
}
